### ISSUE TITLE
Track UML Class Diagrams

### ISSUE THREAD

**Issue by bpprox22** [YsuSERESL/iTrace#48]
We need the ability to track eye movements on UML class diagrams.

**Comment by lmvitullo** [comment]
Here is the stack trace of the NoClassDefFoundError:
@onebenclark  @nickiovino  @shbonita 

!ENTRY org.eclipse.ui 4 4 2016-11-30 22:53:38.998
!MESSAGE An internal error has occurred.
!STACK 0
java.lang.NoClassDefFoundError: edu/ysu/onionuml/ui/graphics/figures/ClassFigure
	at edu.ysu.itrace.ClassMLManager.getUMLE(ClassMLManager.java:269)
	at edu.ysu.itrace.gaze.handlers.ClassMLGazeHandler.handleGaze(ClassMLGazeHandler.java:37)
	at edu.ysu.itrace.gaze.handlers.ClassMLGazeHandler.handleGaze(ClassMLGazeHandler.java:1)
	at edu.ysu.itrace.ControlView.handleGaze(ControlView.java:728)
	at edu.ysu.itrace.ControlView.access$1(ControlView.java:702)
	at edu.ysu.itrace.ControlView$1.runInUIThread(ControlView.java:136)
	at org.eclipse.ui.progress.UIJob$1.run(UIJob.java:97)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4203)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3819)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
